// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_NEW Status = 0
	Status_ACK Status = 1
	Status_ERR Status = 2
)

var Status_name = map[int32]string{
	0: "NEW",
	1: "ACK",
	2: "ERR",
}
var Status_value = map[string]int32{
	"NEW": 0,
	"ACK": 1,
	"ERR": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_record_7eca3f8e50d17d45, []int{0}
}

type Record struct {
	Crc                  uint32               `protobuf:"varint,1,opt,name=crc" json:"crc,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Status               Status               `protobuf:"varint,3,opt,name=status,enum=pb.Status" json:"status,omitempty"`
	Topic                string               `protobuf:"bytes,4,opt,name=topic" json:"topic,omitempty"`
	Cluster              string               `protobuf:"bytes,5,opt,name=cluster" json:"cluster,omitempty"`
	Payload              []byte               `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_record_7eca3f8e50d17d45, []int{0}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetCrc() uint32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *Record) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Record) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NEW
}

func (m *Record) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Record) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Record) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "pb.Record")
	proto.RegisterEnum("pb.Status", Status_name, Status_value)
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_record_7eca3f8e50d17d45) }

var fileDescriptor_record_7eca3f8e50d17d45 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0xc7, 0x7d, 0x77, 0x6d, 0x4a, 0x9f, 0x55, 0x8e, 0xe0, 0x10, 0xba, 0x18, 0xea, 0x12, 0x1c,
	0x52, 0xa8, 0x8b, 0xab, 0x4a, 0x27, 0xc1, 0xe1, 0x29, 0x08, 0x6e, 0x97, 0xf4, 0x2c, 0x85, 0x3b,
	0x12, 0x72, 0xb9, 0xc1, 0x7f, 0xcf, 0xbf, 0x4c, 0x2e, 0x67, 0x74, 0xfb, 0xfe, 0xf8, 0xbc, 0x2f,
	0x0f, 0x57, 0xa1, 0xb1, 0x2e, 0x1c, 0xb4, 0x0f, 0x2e, 0x3a, 0x5e, 0x78, 0xb3, 0xbe, 0x3e, 0x3a,
	0x77, 0x6c, 0x9b, 0x6d, 0x4a, 0xcc, 0xf0, 0xb9, 0x8d, 0xa7, 0xae, 0xe9, 0x63, 0xdd, 0xf9, 0x09,
	0xda, 0x7c, 0x03, 0x32, 0x4a, 0x57, 0xbc, 0xc2, 0xd2, 0x06, 0x2b, 0x40, 0x82, 0xba, 0xa0, 0x51,
	0xf2, 0x7b, 0x5c, 0xfe, 0xf1, 0xa2, 0x90, 0xa0, 0xce, 0x77, 0x6b, 0x3d, 0x2d, 0xea, 0xbc, 0xa8,
	0xdf, 0x32, 0x41, 0xff, 0x30, 0xdf, 0x20, 0xeb, 0x63, 0x1d, 0x87, 0x5e, 0x94, 0x12, 0xd4, 0xe5,
	0x0e, 0xb5, 0x37, 0xfa, 0x35, 0x25, 0xf4, 0xdb, 0xf0, 0x2b, 0x9c, 0x47, 0xe7, 0x4f, 0x56, 0xcc,
	0x24, 0xa8, 0x25, 0x4d, 0x86, 0x0b, 0x5c, 0xd8, 0x76, 0xe8, 0x63, 0x13, 0xc4, 0x3c, 0xe5, 0xd9,
	0x8e, 0x8d, 0xaf, 0xbf, 0x5a, 0x57, 0x1f, 0x04, 0x93, 0xa0, 0x56, 0x94, 0xed, 0xed, 0x0d, 0xb2,
	0x69, 0x9b, 0x2f, 0xb0, 0x7c, 0xd9, 0xbf, 0x57, 0x67, 0xa3, 0x78, 0x78, 0x7a, 0xae, 0x60, 0x14,
	0x7b, 0xa2, 0xaa, 0x78, 0x9c, 0x7d, 0x14, 0xde, 0x18, 0x96, 0xfe, 0xbe, 0xfb, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0x63, 0x32, 0xfc, 0x2b, 0x01, 0x00, 0x00,
}
